---
apiVersion: v1
kind: Service
metadata:
  name: id-generator-api
  namespace: id-generator
spec:
  ports:
    - name: http
      port: 5055
      protocol: TCP
  selector:
    app.kubernetes.io/app: id-generator