{
 "title": "cAdvisor monitoring dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "pod_namespace",
    "query": {
     "query": "label_values(container_label_io_kubernetes_pod_namespace)"
    }
   },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values({container_label_io_kubernetes_pod_namespace=\"$pod_namespace\"},container_label_io_kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU usage % (1m avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum(machine_cpu_cores{namespace=\"cadvisor\", namespace=\"cadvisor\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster memory usage % ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"}) / sum(machine_memory_bytes{namespace=\"cadvisor\", namespace=\"cadvisor\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU usage % of the limit (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum(machine_cpu_cores{namespace=\"cadvisor\", namespace=\"cadvisor\"}) * 100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Cluster memory usage % of the limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"}) / sum(machine_memory_bytes{namespace=\"cadvisor\", namespace=\"cadvisor\"}) * 100",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "CPU used (Cores)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{id=\"/\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU total (Cores)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{namespace=\"cadvisor\", namespace=\"cadvisor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{namespace=\"cadvisor\", namespace=\"cadvisor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pod resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Pods CPU throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(\n    container_cpu_cfs_throttled_seconds_total{\nimage!=\"\",name=~\"^k8s_.*\",container_label_io_kubernetes_pod_namespace=~\"$pod_namespace$\",container_label_io_kubernetes_pod_name=~\"$pod_name$\",\ncontainer_label_io_kubernetes_docker_type=\"container\"\n    }[1m]\n)",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Pods CPU usage (1m avg) with requests and limits",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_label_io_kubernetes_pod_namespace=~\"$pod_namespace$\",container_label_io_kubernetes_pod_name=~\"$pod_name$\",\ncontainer_label_io_kubernetes_docker_type=\"container\"\n}[1m])) by (\n    container_label_io_kubernetes_pod_name\n)",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_limits{\n        namespace=~\"$pod_namespace$\",\n        pod=~\"$pod_name$\",\n        resource=\"cpu\",\n        unit=\"core\"\n    }\n)",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_requests{\n        namespace=~\"$pod_namespace$\",\n        pod=~\"$pod_name$\",\n        resource=\"cpu\",\n        unit=\"core\"\n    }\n)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Pods memory usage with requests and limits",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_label_io_kubernetes_pod_namespace=~\"$pod_namespace$\",\ncontainer_label_io_kubernetes_pod_name=~\"$pod_name$\",\ncontainer_label_io_kubernetes_docker_type=\"container\"\n}) by (\n    container_label_io_kubernetes_pod_name\n)",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_limits{\n        namespace=~\"$pod_namespace$\",\n        pod=~\"$pod_name$\",\n        resource=\"memory\",\n        unit=\"byte\"\n    }\n)",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_requests{\n        namespace=~\"$pod_namespace$\",\n        pod=~\"$pod_name$\",\n        resource=\"memory\",\n        unit=\"byte\"\n    }\n)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(\n  container_network_receive_bytes_total{\n    image!=\"\",\n    name=~\"^k8s_.*\",container_label_io_kubernetes_pod_namespace=~\"$pod_namespace$\",container_label_io_kubernetes_pod_name=~\"$pod_name$\"\n  }[1m]\n) * 8",
     "legendFormat": "Receive - {{container_label_io_kubernetes_pod_name}}"
    },
    {
     "expr": "irate(\n  container_network_transmit_bytes_total{\n    image!=\"\",\n    name=~\"^k8s_.*\",\ncontainer_label_io_kubernetes_pod_namespace=~\"$pod_namespace$\",container_label_io_kubernetes_pod_name=~\"$pod_name$\"\n  }[1m]\n) * 8",
     "legendFormat": "Transmit - {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  }
 ]
}