---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-gateway-podmonitor
  namespace: proxy-monitoring
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - istio-ingress
  selector:
    matchLabels:
      app: istio-gateway
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: stats/prometheus
      interval: 15s
      scrapeTimeout: 15s