---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-service-v2
  namespace: test-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: test-service
      version: v2
  template:
    metadata:
      labels:
        app.kubernetes.io/app: test-service
        version: v2
        istio: monitor
    spec:
      serviceAccountName: test-service-sa
      containers:
        - image: test-service:1.0
          imagePullPolicy: Never
          name: test-service
          env:
            - name: SERVICE
              value: test-service
            - name: VERSION
              value: v2
          ports:
            - name: http
              containerPort: 5055