apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: test-service-destination-rule
  namespace: test-service
spec:
  host: test-service-server.test-service.svc.cluster.local
  subsets:
    - name: v1
      labels:
        app.kubernetes.io/app: test-service
        version: v1
    - name: v2
      labels:
        app.kubernetes.io/app: test-service
        version: v2