apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-service-route
  namespace: test-service
spec:
  hosts:
  - test-service-server.test-service.svc.cluster.local # DNS for internal access
  http:
  - name: "test-service-route"
    # match:
    # - uri:
    #   prefix: /
    route:
    - destination:
        host: test-service-server.test-service.svc.cluster.local
        subset: v1
      weight: 90
    - destination:
        host: test-service-server.test-service.svc.cluster.local
        subset: v2
      weight: 10