---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxy-podmonitor
  namespace: proxy-monitoring
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - proxy-server
  selector:
    matchLabels:
      istio: monitor
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: stats/prometheus
      interval: 15s
      scrapeTimeout: 15s