apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-server
  namespace: proxy-server
  labels:
    app.kubernetes.io/name: proxy-server
spec:
  replicas: 1 #number of replicas generated  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # The maxSurge property controls the maximum number of additional pods that can be created during a rolling update
      maxUnavailable: 1 # The maxUnavailable property determines the maximum number or percentage of pods that can be unavailable during a rolling update
      # maxSurge: 25%
      # maxUnavailable: 25%
  selector:
    # Assigns labels to the pods for future selection
    matchLabels:
      app.kubernetes.io/app: proxy-server
  template:
    metadata:
      annotations:
        # https://istio.io/latest/docs/reference/config/annotations/
        # port 8200 is vault port
        # traffic.sidecar.istio.io/excludeOutboundPorts: "8200"
        sidecar.istio.io/proxyCPU: "500m"
        sidecar.istio.io/proxyCPULimit: "500m"
        sidecar.istio.io/proxyMemory: "256Mi"
        sidecar.istio.io/proxyMemoryLimit: "256Mi"
        # vault.hashicorp.com/agent-inject: "true"
        # vault.hashicorp.com/tls-skip-verify: "true"        
        # vault.hashicorp.com/agent-inject-secret-jwt-secret-key : "key/jwt-secret-key"
        # vault.hashicorp.com/agent-inject-template-jwt-secret-key: |
        #   {{- with secret "key/jwt-secret-key" -}}
        #     {{ .Data | toJSON }}
        #   {{- end }}
        # vault.hashicorp.com/role: "multiple-role"
      labels:
        app.kubernetes.io/app: proxy-server
        istio: monitor
        service.istio.io/canonical-name: proxy-server
    spec:
      serviceAccountName: proxy-server-sa
      containers:
      - name: proxy-server
        image: proxy-server:1.0
        imagePullPolicy: Never
        env:
        - name: SERVICE
          value: proxy-server
        - name: APP_ENV
          value: "production"
        - name: APP_PORT
          value: "3000"
        - name: APP_SECRET_PATH
          valueFrom:
            configMapKeyRef:
              name: proxy-server-config
              key: app_secret_path
        - name: APP_OTEL_COL_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: proxy-server-config
              key: app_otel_col_endpoint
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          runAsUser: 10001
          runAsGroup: 10001
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 3000
          name: http
        resources:          
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 400m
            memory: 128Mi